@@ .. @@
             .sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
             .authorizeHttpRequests(authz -> authz
-                .requestMatchers("/auth/**").permitAll()
-                .requestMatchers("/gyms/nearby").permitAll()
-                .requestMatchers("/gyms/search").permitAll()
-                .requestMatchers("/gyms/{id}").permitAll()
-                .requestMatchers("/gyms").hasRole("ADMIN")
-                .requestMatchers("/bookings/**").hasAnyRole("USER", "ADMIN")
-                .requestMatchers("/users/**").hasAnyRole("USER", "ADMIN")
-                .requestMatchers("/ai/**").hasAnyRole("USER", "ADMIN")
+                .requestMatchers("/api/auth/**").permitAll()
+                .requestMatchers("/api/gyms/nearby").permitAll()
+                .requestMatchers("/api/gyms/search").permitAll()
+                .requestMatchers("/api/gyms/{id}").permitAll()
+                .requestMatchers("/api/gyms").hasRole("ADMIN")
+                .requestMatchers("/api/bookings/**").hasAnyRole("USER", "ADMIN")
+                .requestMatchers("/api/users/**").hasAnyRole("USER", "ADMIN")
+                .requestMatchers("/api/ai/**").hasAnyRole("USER", "ADMIN")
                 .anyRequest().authenticated()
             )
             .addFilterBefore(jwtAuthenticationFilter(), UsernamePasswordAuthenticationFilter.class);